name: Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Echo token
        run: echo "The token is $NODE_AUTH_TOKEN"
        
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Log in to npm registry
        run: echo "//npm.key=$NODE_AUTH_TOKEN"

      - name: Publish package
        run: npm publish --access public
